name: Docker Image CI

on: 
  pull_request:
    types: [opened, synchronize]

jobs:

  build:
    
    name: simple-ci

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag codefresh-sa/express-app:${{ github.event.pull_request.head.sha }}

    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2.5.1
      with:
        image: codefresh-sa/express-app
        tags: ${{ github.event.pull_request.head.sha }}
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.SA_JSON }}

    - name: Report Image to Codefresh
      uses: codefresh-io/codefresh-report-image@latest
      with:
        CF_PLATFORM_URL: 'https://cf.pov.sales-dev.codefresh.io'
        CF_RUNTIME_NAME: 'pov-codefresh-istio-runtime'
        CF_API_KEY: '${{ secrets.CF_API_KEY }}'
        CF_IMAGE: 'gcr.io/codefresh-sa/express-app:${{ github.event.pull_request.head.sha }}'
        CF_REGISTRY_USERNAME: '_json_key'
        CF_REGISTRY_PASSWORD: '${{ secrets.SA_JSON }}'
        CF_REGISTRY_DOMAIN: 'gcr.io'
        CF_GIT_BRANCH: '${{ github.head_ref }}'
        CF_GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        CF_JIRA_INTEGRATION: 'cf-demo-jira'
        CF_JIRA_PROJECT_PREFIX: 'KPT'
        CF_JIRA_MESSAGE: '${{ github.event.pull_request.head.ref }}'
        CF_ENRICHERS: 'git, jira'
        CF_LOGS_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        CF_WORKFLOW_NAME: ${{ github.workflow }}
        CF_WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}